services:
  - mysql
before_install:
  - mysql -u root --password="" < back-end/database/database.sql
  - use appointment_booking_system;
  - source back-end/database/test_data.sql;
matrix:
  include:
    - language: php
      php: "7.4"
      before_install:
        - composer self-update
      before_script:
        - cd back-end
        - composer install
      script: phpunit --configuration phpunit.xml

    - language: node_js
      node_js: "node"
      before_script:
        - cd front-end
        - npm i
