matrix:
  include:
    - language: php
      php: "7.4"
      services:
        - mysql  
      before_install:
        - mysql -u root --password="" < back-end/database/database.sql
        - mysql -u root --password="" appointment_booking_system  < back-end/database/test_data.sql
        - composer self-update
      before_script:
        - composer install
      script: vendor/bin/phpunit --configuration phpunit.xml

    # - language: node_js
    #   node_js: "node"
    #   before_script:
    #     - npm i
    #   script: http-server -p 80 & npm test &
